FROM maven:3.9-eclipse-temurin-17-alpine AS build
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline -q
COPY src ./src
RUN mvn package -DskipTests -q

FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=build /app/target/symptom-checker-backend-1.0.0.jar app.jar


EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
